[package]
name = "player-remux-ffmpeg"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]
name = "vesper_remux_ffmpeg"

[dependencies]
ffmpeg-next = { workspace = true, features = ["codec", "format"] }
player-plugin = { package = "vesper-player-plugin", path = "../../plugin/player-plugin" }
thiserror.workspace = true
