[workspace]
members = [
    "crates/model/*",
    "crates/core/*",
    "crates/ffi/*",
    "crates/plugin/*",
    "crates/plugin-decoder/*",
    "crates/plugin-remux/*",
    "crates/audio/*",
    "crates/render/*",
    "crates/backend/*",
    "crates/platform/common/*",
    "crates/platform/desktop/*",
    "crates/platform/mobile/*",
    "crates/platform/jni/*",
    "crates/tools/*",
    "examples/basic-player",
]
resolver = "3"

[workspace.package]
authors = ["umbrella22"]
edition = "2024"
homepage = "https://github.com/umbrella22/Vesper"
license = "Apache-2.0"
repository = "https://github.com/umbrella22/Vesper"
rust-version = "1.98"
version = "0.5.1"

[workspace.dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
cpal = "0.18.1"
crossbeam-queue = "0.3.13"
dlmalloc = { version = "0.2.14", features = ["global"] }
ed25519-dalek = "3.0.0"
ffmpeg-next = { version = "9.0.0", default-features = false }
flate2 = "1.1.9"
getrandom = "0.4.3"
hex = "0.4.3"
indexmap = { version = "2.14.0", features = ["serde"] }
libloading = "0.9.0"
nix = { version = "0.31.3", default-features = false, features = ["process", "signal"] }
pollster = "1.0.1"
proc-macro2 = "1.0.107"
quick-xml = "0.42.0"
quote = "1.0.47"
regex = "1.13.1"
rustix = { version = "1.1.4", features = ["fs"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
semver = "1.0.28"
sha1 = "0.11.0"
sha2 = "0.11.0"
signal-hook = "0.4.4"
syn = { version = "3.0.3", features = ["full"] }
tar = "0.4.46"
tempfile = "3.27.0"
thiserror = "2.0.19"
toml = { version = "1.1.4", features = ["preserve_order"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "fmt"] }
unicode-casefold = "0.2.0"
unicode-normalization = "0.1.25"
url = "2.5.8"
uuid = { version = "1.24.0", features = ["serde"] }
wasmtime = { version = "48.0.1", default-features = false, features = ["anyhow", "component-model", "cranelift", "runtime", "std"] }
wat = "1.255.0"
wit-bindgen = { version = "0.61.1", default-features = false, features = ["macros", "realloc"] }
wit-component = "0.258.0"
wit-parser = "0.258.0"
zip = { version = "8.6.0", default-features = false }
xz2 = "0.1.7"
x509-parser = "0.18.1"
wgpu = "30.0.0"
winit = "0.30.13"

[profile.release]
codegen-units = 1
lto = "thin"
strip = "debuginfo"
