[package]
name = "player-plugin-loader"
description = "Checked native and WASM loader wrappers for the Vesper plugin platform."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
installed-catalog = ["dep:player-plugin-package"]
wasm = ["dep:player-plugin-wasm-host"]

[dependencies]
hex.workspace = true
libloading.workspace = true
player-plugin = { version = "0.4.3", path = "../player-plugin" }
player-plugin-abi = { version = "0.4.3", path = "../player-plugin-abi" }
player-plugin-package = { version = "0.4.3", path = "../player-plugin-package", optional = true }
player-plugin-wasm-host = { version = "0.4.3", path = "../player-plugin-wasm-host", optional = true }
serde.workspace = true
serde_json.workspace = true
semver.workspace = true
sha2.workspace = true
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true
zip.workspace = true

[dev-dependencies]
tempfile.workspace = true
wat.workspace = true
wit-component.workspace = true
wit-parser.workspace = true
