[package]
name = "player-decoder-videotoolbox"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[lib]
name = "vesper_decoder_videotoolbox"
crate-type = ["cdylib", "rlib"]

[dependencies]
player-plugin = { package = "vesper-player-plugin", path = "../../plugin/player-plugin" }
