schema_version = 1

[compatibility]
requirement = ">=9.0.0, <9.1.0"
default_series = "9.0"

[release]
version = "9.0.1"
source_url = "https://ffmpeg.org/releases/ffmpeg-9.0.1.tar.xz"
source_sha256 = "cf38e0e28c7e5605942c4a77755349b0145804a397af37eb1fb4c77cb237f635"
