[package]
name = "vesper-player-plugin-wasm-host"
description = "Bounded Wasmtime host adapters for Vesper WASM EventHook and BenchmarkSink plugins."
authors.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
documentation = "https://docs.rs/vesper-player-plugin-wasm-host"
readme = "README.md"
keywords = ["vesper", "media", "plugin", "wasm", "wasmtime"]
categories = ["wasm", "multimedia"]
publish = ["crates-io"]

[lib]
name = "player_plugin_wasm_host"

[dependencies]
player-plugin = { package = "vesper-player-plugin", version = "0.5.1", path = "../player-plugin" }
thiserror.workspace = true
tracing.workspace = true
wasmtime.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true
wat.workspace = true
wit-component.workspace = true
wit-parser.workspace = true
