[package]
name = "player-backend-ffmpeg"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
ffmpeg-next = { workspace = true, features = [
    "codec",
    "filter",
    "format",
    "software-resampling",
    "software-scaling",
] }
player-model = { path = "../../model/player-model" }
player-plugin = { package = "vesper-player-plugin", path = "../../plugin/player-plugin" }
tracing.workspace = true
url.workspace = true
