#ifndef PLAYER_FFI_H
#define PLAYER_FFI_H

/* Auto-generated by cbindgen. Do not edit this file directly. */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#define PLAYER_FFI_MIN_PLAYBACK_RATE 0.5f
#define PLAYER_FFI_NATURAL_PLAYBACK_RATE_MAX 2.0f
#define PLAYER_FFI_MAX_PLAYBACK_RATE 3.0f


typedef enum PlayerFfiErrorCode {
  PLAYER_FFI_ERROR_CODE_NONE = 0,
  PLAYER_FFI_ERROR_CODE_NULL_POINTER = 1,
  PLAYER_FFI_ERROR_CODE_INVALID_UTF8 = 2,
  PLAYER_FFI_ERROR_CODE_INVALID_ARGUMENT = 3,
  PLAYER_FFI_ERROR_CODE_INVALID_STATE = 4,
  PLAYER_FFI_ERROR_CODE_INVALID_SOURCE = 5,
  PLAYER_FFI_ERROR_CODE_BACKEND_FAILURE = 6,
  PLAYER_FFI_ERROR_CODE_AUDIO_OUTPUT_UNAVAILABLE = 7,
  PLAYER_FFI_ERROR_CODE_DECODE_FAILURE = 8,
  PLAYER_FFI_ERROR_CODE_SEEK_FAILURE = 9,
  PLAYER_FFI_ERROR_CODE_UNSUPPORTED = 10,
} PlayerFfiErrorCode;

typedef enum PlayerFfiEventKind {
  PLAYER_FFI_EVENT_KIND_INITIALIZED = 0,
  PLAYER_FFI_EVENT_KIND_METADATA_READY = 1,
  PLAYER_FFI_EVENT_KIND_FIRST_FRAME_READY = 2,
  PLAYER_FFI_EVENT_KIND_PLAYBACK_STATE_CHANGED = 3,
  PLAYER_FFI_EVENT_KIND_BUFFERING_CHANGED = 4,
  PLAYER_FFI_EVENT_KIND_VIDEO_SURFACE_CHANGED = 5,
  PLAYER_FFI_EVENT_KIND_AUDIO_OUTPUT_CHANGED = 6,
  PLAYER_FFI_EVENT_KIND_PLAYBACK_RATE_CHANGED = 7,
  PLAYER_FFI_EVENT_KIND_SEEK_COMPLETED = 8,
  PLAYER_FFI_EVENT_KIND_ERROR = 9,
  PLAYER_FFI_EVENT_KIND_ENDED = 10,
  PLAYER_FFI_EVENT_KIND_INTERRUPTION_CHANGED = 11,
} PlayerFfiEventKind;

typedef enum PlayerFfiVideoDecodeMode {
  PLAYER_FFI_VIDEO_DECODE_MODE_SOFTWARE = 0,
  PLAYER_FFI_VIDEO_DECODE_MODE_HARDWARE = 1,
} PlayerFfiVideoDecodeMode;

typedef enum PlayerFfiMediaSourceKind {
  PLAYER_FFI_MEDIA_SOURCE_KIND_LOCAL = 0,
  PLAYER_FFI_MEDIA_SOURCE_KIND_REMOTE = 1,
} PlayerFfiMediaSourceKind;

typedef enum PlayerFfiMediaSourceProtocol {
  PLAYER_FFI_MEDIA_SOURCE_PROTOCOL_UNKNOWN = 0,
  PLAYER_FFI_MEDIA_SOURCE_PROTOCOL_FILE = 1,
  PLAYER_FFI_MEDIA_SOURCE_PROTOCOL_CONTENT = 2,
  PLAYER_FFI_MEDIA_SOURCE_PROTOCOL_PROGRESSIVE = 3,
  PLAYER_FFI_MEDIA_SOURCE_PROTOCOL_HLS = 4,
  PLAYER_FFI_MEDIA_SOURCE_PROTOCOL_DASH = 5,
} PlayerFfiMediaSourceProtocol;

typedef enum PlayerFfiTrackKind {
  PLAYER_FFI_TRACK_KIND_VIDEO = 0,
  PLAYER_FFI_TRACK_KIND_AUDIO = 1,
  PLAYER_FFI_TRACK_KIND_SUBTITLE = 2,
} PlayerFfiTrackKind;

typedef enum PlayerFfiTrackSelectionMode {
  PLAYER_FFI_TRACK_SELECTION_MODE_AUTO = 0,
  PLAYER_FFI_TRACK_SELECTION_MODE_DISABLED = 1,
  PLAYER_FFI_TRACK_SELECTION_MODE_TRACK = 2,
} PlayerFfiTrackSelectionMode;

typedef enum PlayerFfiAbrMode {
  PLAYER_FFI_ABR_MODE_AUTO = 0,
  PLAYER_FFI_ABR_MODE_CONSTRAINED = 1,
  PLAYER_FFI_ABR_MODE_FIXED_TRACK = 2,
} PlayerFfiAbrMode;

typedef enum PlayerFfiPlaybackState {
  PLAYER_FFI_PLAYBACK_STATE_READY = 0,
  PLAYER_FFI_PLAYBACK_STATE_PLAYING = 1,
  PLAYER_FFI_PLAYBACK_STATE_PAUSED = 2,
  PLAYER_FFI_PLAYBACK_STATE_FINISHED = 3,
} PlayerFfiPlaybackState;

typedef enum PlayerFfiCallStatus {
  PLAYER_FFI_CALL_STATUS_OK = 0,
  PLAYER_FFI_CALL_STATUS_ERROR = 1,
} PlayerFfiCallStatus;

typedef enum PlayerFfiPixelFormat {
  PLAYER_FFI_PIXEL_FORMAT_RGBA8888 = 0,
  PLAYER_FFI_PIXEL_FORMAT_YUV420P = 1,
} PlayerFfiPixelFormat;

typedef enum PlayerFfiCommandKind {
  PLAYER_FFI_COMMAND_KIND_PLAY = 0,
  PLAYER_FFI_COMMAND_KIND_PAUSE = 1,
  PLAYER_FFI_COMMAND_KIND_TOGGLE_PAUSE = 2,
  PLAYER_FFI_COMMAND_KIND_SEEK_TO = 3,
  PLAYER_FFI_COMMAND_KIND_STOP = 4,
} PlayerFfiCommandKind;

typedef enum PlayerFfiTimelineKind {
  PLAYER_FFI_TIMELINE_KIND_VOD = 0,
  PLAYER_FFI_TIMELINE_KIND_LIVE = 1,
  PLAYER_FFI_TIMELINE_KIND_LIVE_DVR = 2,
} PlayerFfiTimelineKind;

typedef struct PlayerFfiError {
  enum PlayerFfiErrorCode code;
  char *message;
} PlayerFfiError;

typedef struct PlayerFfiAudioOutputInfo {
  char *device_name;
  bool has_channels;
  uint16_t channels;
  bool has_sample_rate;
  uint32_t sample_rate;
  char *sample_format;
} PlayerFfiAudioOutputInfo;

typedef struct PlayerFfiDecodedAudioSummary {
  uint16_t channels;
  uint32_t sample_rate;
  uint64_t duration_ms;
} PlayerFfiDecodedAudioSummary;

typedef struct PlayerFfiVideoDecodeInfo {
  enum PlayerFfiVideoDecodeMode selected_mode;
  bool hardware_available;
  char *hardware_backend;
  char *fallback_reason;
} PlayerFfiVideoDecodeInfo;

typedef struct PlayerFfiStartup {
  bool ffmpeg_initialized;
  bool has_audio_output;
  struct PlayerFfiAudioOutputInfo audio_output;
  bool has_decoded_audio;
  struct PlayerFfiDecodedAudioSummary decoded_audio;
  bool has_video_decode;
  struct PlayerFfiVideoDecodeInfo video_decode;
} PlayerFfiStartup;

typedef struct PlayerFfiVideoInfo {
  char *codec;
  uint32_t width;
  uint32_t height;
  bool has_frame_rate;
  double frame_rate;
} PlayerFfiVideoInfo;

typedef struct PlayerFfiAudioInfo {
  char *codec;
  uint32_t sample_rate;
  uint16_t channels;
} PlayerFfiAudioInfo;

typedef struct PlayerFfiTrack {
  char *id;
  enum PlayerFfiTrackKind kind;
  char *label;
  char *language;
  char *codec;
  bool has_bit_rate;
  uint64_t bit_rate;
  bool has_width;
  uint32_t width;
  bool has_height;
  uint32_t height;
  bool has_frame_rate;
  double frame_rate;
  bool has_channels;
  uint16_t channels;
  bool has_sample_rate;
  uint32_t sample_rate;
  bool is_default;
  bool is_forced;
} PlayerFfiTrack;

typedef struct PlayerFfiTrackCatalog {
  struct PlayerFfiTrack *tracks;
  size_t len;
  bool adaptive_video;
  bool adaptive_audio;
} PlayerFfiTrackCatalog;

typedef struct PlayerFfiTrackSelection {
  enum PlayerFfiTrackSelectionMode mode;
  char *track_id;
} PlayerFfiTrackSelection;

typedef struct PlayerFfiAbrPolicy {
  enum PlayerFfiAbrMode mode;
  char *track_id;
  bool has_max_bit_rate;
  uint64_t max_bit_rate;
  bool has_max_width;
  uint32_t max_width;
  bool has_max_height;
  uint32_t max_height;
} PlayerFfiAbrPolicy;

typedef struct PlayerFfiTrackSelectionSnapshot {
  struct PlayerFfiTrackSelection video;
  struct PlayerFfiTrackSelection audio;
  struct PlayerFfiTrackSelection subtitle;
  struct PlayerFfiAbrPolicy abr_policy;
} PlayerFfiTrackSelectionSnapshot;

typedef struct PlayerFfiMediaInfo {
  char *source_uri;
  enum PlayerFfiMediaSourceKind source_kind;
  enum PlayerFfiMediaSourceProtocol source_protocol;
  bool has_duration;
  uint64_t duration_ms;
  bool has_bit_rate;
  uint64_t bit_rate;
  size_t audio_streams;
  size_t video_streams;
  bool has_best_video;
  struct PlayerFfiVideoInfo best_video;
  bool has_best_audio;
  struct PlayerFfiAudioInfo best_audio;
  struct PlayerFfiTrackCatalog track_catalog;
  struct PlayerFfiTrackSelectionSnapshot track_selection;
} PlayerFfiMediaInfo;

typedef struct PlayerFfiFirstFrameReady {
  uint64_t presentation_time_ms;
  uint32_t width;
  uint32_t height;
} PlayerFfiFirstFrameReady;

typedef struct PlayerFfiEvent {
  enum PlayerFfiEventKind kind;
  struct PlayerFfiStartup initialized;
  struct PlayerFfiMediaInfo metadata_ready;
  struct PlayerFfiFirstFrameReady first_frame_ready;
  enum PlayerFfiPlaybackState playback_state;
  bool interrupted;
  bool buffering;
  bool surface_attached;
  bool has_audio_output;
  struct PlayerFfiAudioOutputInfo audio_output;
  float playback_rate;
  uint64_t seek_position_ms;
  struct PlayerFfiError error;
} PlayerFfiEvent;

typedef struct PlayerFfiEventList {
  struct PlayerFfiEvent *ptr;
  size_t len;
} PlayerFfiEventList;

typedef struct PlayerFfiInitializerHandle {
  uint8_t _private;
} PlayerFfiInitializerHandle;

typedef struct PlayerFfiHandle {
  uint8_t _private;
} PlayerFfiHandle;

typedef struct PlayerFfiVideoFrame {
  uint64_t presentation_time_ms;
  uint32_t width;
  uint32_t height;
  uint32_t bytes_per_row;
  enum PlayerFfiPixelFormat pixel_format;
  uint8_t *bytes;
  size_t len;
} PlayerFfiVideoFrame;

typedef struct PlayerFfiProgress {
  uint64_t position_ms;
  bool has_duration;
  uint64_t duration_ms;
  bool has_ratio;
  double ratio;
} PlayerFfiProgress;

typedef struct PlayerFfiSeekableRange {
  uint64_t start_ms;
  uint64_t end_ms;
} PlayerFfiSeekableRange;

typedef struct PlayerFfiTimelineSnapshot {
  enum PlayerFfiTimelineKind kind;
  bool is_seekable;
  bool has_seekable_range;
  struct PlayerFfiSeekableRange seekable_range;
  bool has_live_edge;
  uint64_t live_edge_ms;
  uint64_t position_ms;
  bool has_duration;
  uint64_t duration_ms;
  bool has_ratio;
  double ratio;
} PlayerFfiTimelineSnapshot;

typedef struct PlayerFfiSnapshot {
  char *source_uri;
  enum PlayerFfiPlaybackState state;
  bool has_video_surface;
  bool is_interrupted;
  bool is_buffering;
  float playback_rate;
  struct PlayerFfiProgress progress;
  struct PlayerFfiTimelineSnapshot timeline;
  struct PlayerFfiMediaInfo media_info;
} PlayerFfiSnapshot;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

void player_ffi_error_free(struct PlayerFfiError *error);

void player_ffi_event_list_free(struct PlayerFfiEventList *events);

void player_ffi_initializer_destroy(struct PlayerFfiInitializerHandle *handle);

enum PlayerFfiCallStatus player_ffi_initializer_initialize(struct PlayerFfiInitializerHandle *handle,
                                                           struct PlayerFfiHandle **out_player,
                                                           bool *out_has_initial_frame,
                                                           struct PlayerFfiVideoFrame *out_initial_frame,
                                                           struct PlayerFfiStartup *out_startup,
                                                           struct PlayerFfiError *out_error);

enum PlayerFfiCallStatus player_ffi_initializer_media_info(const struct PlayerFfiInitializerHandle *handle,
                                                           struct PlayerFfiMediaInfo *out_media_info,
                                                           struct PlayerFfiError *out_error);

enum PlayerFfiCallStatus player_ffi_initializer_probe_uri(const char *uri,
                                                          struct PlayerFfiInitializerHandle **out_initializer,
                                                          struct PlayerFfiError *out_error);

enum PlayerFfiCallStatus player_ffi_initializer_startup(const struct PlayerFfiInitializerHandle *handle,
                                                        struct PlayerFfiStartup *out_startup,
                                                        struct PlayerFfiError *out_error);

void player_ffi_media_info_free(struct PlayerFfiMediaInfo *media_info);

enum PlayerFfiCallStatus player_ffi_player_advance(struct PlayerFfiHandle *handle,
                                                   struct PlayerFfiVideoFrame *out_frame,
                                                   bool *out_has_frame,
                                                   struct PlayerFfiError *out_error);

void player_ffi_player_destroy(struct PlayerFfiHandle *handle);

enum PlayerFfiCallStatus player_ffi_player_dispatch(struct PlayerFfiHandle *handle,
                                                    enum PlayerFfiCommandKind command,
                                                    uint64_t position_ms,
                                                    bool *out_applied,
                                                    struct PlayerFfiVideoFrame *out_frame,
                                                    struct PlayerFfiSnapshot *out_snapshot,
                                                    struct PlayerFfiError *out_error);

enum PlayerFfiCallStatus player_ffi_player_drain_events(struct PlayerFfiHandle *handle,
                                                        struct PlayerFfiEventList *out_events,
                                                        struct PlayerFfiError *out_error);

enum PlayerFfiCallStatus player_ffi_player_next_deadline_delay_ms(const struct PlayerFfiHandle *handle,
                                                                  bool *out_has_deadline,
                                                                  uint64_t *out_delay_ms,
                                                                  struct PlayerFfiError *out_error);

enum PlayerFfiCallStatus player_ffi_player_set_abr_policy(struct PlayerFfiHandle *handle,
                                                          const struct PlayerFfiAbrPolicy *policy,
                                                          bool *out_applied,
                                                          struct PlayerFfiSnapshot *out_snapshot,
                                                          struct PlayerFfiError *out_error);

enum PlayerFfiCallStatus player_ffi_player_set_audio_track_selection(struct PlayerFfiHandle *handle,
                                                                     const struct PlayerFfiTrackSelection *selection,
                                                                     bool *out_applied,
                                                                     struct PlayerFfiSnapshot *out_snapshot,
                                                                     struct PlayerFfiError *out_error);

enum PlayerFfiCallStatus player_ffi_player_set_playback_rate(struct PlayerFfiHandle *handle,
                                                             float playback_rate,
                                                             bool *out_applied,
                                                             struct PlayerFfiSnapshot *out_snapshot,
                                                             struct PlayerFfiError *out_error);

enum PlayerFfiCallStatus player_ffi_player_set_subtitle_track_selection(struct PlayerFfiHandle *handle,
                                                                        const struct PlayerFfiTrackSelection *selection,
                                                                        bool *out_applied,
                                                                        struct PlayerFfiSnapshot *out_snapshot,
                                                                        struct PlayerFfiError *out_error);

enum PlayerFfiCallStatus player_ffi_player_set_video_track_selection(struct PlayerFfiHandle *handle,
                                                                     const struct PlayerFfiTrackSelection *selection,
                                                                     bool *out_applied,
                                                                     struct PlayerFfiSnapshot *out_snapshot,
                                                                     struct PlayerFfiError *out_error);

enum PlayerFfiCallStatus player_ffi_player_snapshot(const struct PlayerFfiHandle *handle,
                                                    struct PlayerFfiSnapshot *out_snapshot,
                                                    struct PlayerFfiError *out_error);

void player_ffi_snapshot_free(struct PlayerFfiSnapshot *snapshot);

void player_ffi_startup_free(struct PlayerFfiStartup *startup);

void player_ffi_video_frame_free(struct PlayerFfiVideoFrame *frame);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* PLAYER_FFI_H */
