org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
vesper.player.android.abis=arm64-v8a
vesper.player.android.sourceNormalizerJniLibs=../../../examples/flutter-host/build/app/generated/playerSourceNormalizerFfmpeg/jniLibs
vesper.player.android.frameProcessorDiagnosticJniLibs=../../../examples/flutter-host/build/app/generated/playerFrameProcessorDiagnostic/jniLibs
# Flutter 3.47's Gradle plugin still casts the Android extension to the legacy type.
android.builtInKotlin=false
android.newDsl=false
