[package]
name = "player-source-normalizer-ffmpeg"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[lib]
name = "vesper_source_normalizer_ffmpeg"
crate-type = ["cdylib", "rlib"]

[dependencies]
ffmpeg-next = { workspace = true, features = ["codec", "format"] }
player-plugin = { path = "../player-plugin" }
player-source-normalizer = { path = "../../core/player-source-normalizer" }
toml.workspace = true
url.workspace = true
